### ISSUE TITLE
noddos messes up cron file

### ISSUE THREAD

**Issue by UniverseXXX** [noddos/noddos#42] opened 2017-11-29 08:30 UTC
Each time noddos writes into a cron file it puts all commented out lines at the top of the file and the commands at the bottom with noddos on the last line. My understanding that noddos should search for the noddos command line and just replace it. 

> #Adblock lists updates every day at 3am
> #DNSCrypt resolver file updates every Tuesday and Friday at 4am
> #Mamba fan script runs every 5 minutes
> #Note: To avoid infinite reboot loop, wait 70 seconds
> #Reboot at 2:30am every Thursday
> #and touch a file in /etc so clock will be set
> #properly to 2:31 on reboot before cron starts.
> #0 0 * * * /etc/init.d/acme start
> #30 6,14,22 * * * /etc/init.d/openvpn-policy-routing reload
> #LetsEncrypt checks certificate every midnight
> #NoDDoS updates
> #OpenVPN Policy Routing restarts every day at 6:30, 14:30, 22:30
> #Switch Off WiFi every day from 1am till 5am
> */5 * * * * /sbin/fan_ctrl.sh
> 0 1 * * * /usr/bin/wifi_schedule.sh forcestop
> 0 3 * * * /etc/init.d/adblock start
> 0 0,4,8,12,16,20 * * * sh /etc/upgraderesolv.sh
> 0 5 * * * /usr/bin/wifi_schedule.sh start
> 30 2 * * 4 sleep 70 && touch /etc/banner && reboot
> 50 */3 * * * /usr/bin/getnoddosdeviceprofiles;  if [ $? -gt 0 ]; then service noddos reload; fi

**Comment by StevenHessing** [comment] 2018-01-14 15:53
Which version of Noddos are you using? The openwrt init script in the master branch of noddos checks if there is already a cronjob and if not, appends a line to the crontab of the root user.

**Comment by StevenHessing** [comment] 2018-03-19 03:18
closing out bug as I can't reproduce it and no feedback was provided by the submitted of the bug

**Closed by StevenHessing** 2018-03-19 03:18 UTC
Labels: bug, no repro
